In [5]:
import numpy as np 

In [12]:
my_array = np.array([1, 2, 3, 4, 5]) # NumPy中的数组类被称为ndarray，要注意的是numpy.array与Python标准库中的array.array是不同的

In [ ]:
n = my_array.ndim  # 取数组的维度 

In [13]:
print(n)

1


In [14]:
print(my_array.shape) # ndarray.shape是一个整型tuple，用来表示数组中的每个维度的大小。例如，对于一个n行和m列的矩阵，其shape为(n,m)。

(5,)


In [15]:
print(my_array.size)

5


In [17]:
zero_arr = np.zeros

In [18]:
print(zero_arr)

<built-in function zeros>


In [19]:
zero_arr2 = np.zeros(5)

In [20]:
print(zero_arr2)

[0. 0. 0. 0. 0.]


In [21]:
random_arr = random.rand(3,4)

In [22]:
print(random_arr)

[[0.30073339 0.77090786 0.77190516 0.05301396]
 [0.39519074 0.81579696 0.24305861 0.18032531]
 [0.91607574 0.86727894 0.61738347 0.36805027]]
